ersion: 2.1

jobs:
  print:
    docker:
      - image: cimg/node:lts  
    environment:
      MyLastName : Aly
    steps:
      - checkout
      - run:
          name: type my name
          command: |
            echo $MyFirstName
            echo $MyLastName
            echo "My name is hany" > mname.txt

      - save_cache:
          key: v1-my-project-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

      - persist_to_workspace:
          root: ~/
          paths:
            - mname.txt
            #- target/application.jar
            #- build/*

  testSharing:
    docker:
      - image: cimg/node:lts  
    environment:
      MyLastName : Aly
    steps:
      - run:
          name: create workspace folder
          command: |
            mkdir workspace
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run:
          name: type my name
          command: |
            echo $MyFirstName
            echo $MyLastName
            cat ~/workspace/mname.txt
      #- restore_cache:
      #    keys:
      #      - v1-my-project-{{ checksum "project.clj" }}
      #      - v1-my-project-

          
workflows:
  default: 
    jobs:
      - print
      - testSharing:
          requires:
            - print
