version: 2.1

jobs:
  print:
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: type my name
          command: |
            echo ${MyFirstName}
workflows:
  default: 
    jobs:
      - print