version: 2.1

jobs:
  print:
    docker:
      - image: cimg/node:lts
    environment:
      myName: <<MyFirstName>>
    steps:
      - run:
          name: type my name
          command: |
            echo $myName
            echo
workflows:
  default: 
    jobs:
      - print