version: 2.1

jobs:
  print:
    docker:
      - image: cimg/base:2022.06 
    environment:
      MyLastName : Aly
    steps:
      - checkout
      - run:
          name: type my name
          command: |
            echo $MyFirstName
            echo $MyLastName
            echo "My name is hany" > ~/mname.txt

      - persist_to_workspace:
          root: ~/workspace1
          paths:
            - mname.txt
            #- target/application.jar
            #- build/*

      #- save_cache:
      #    key: v1-my-project-{{ checksum "project.clj" }}
      #    paths:
      #      - ~/.m2

  testSharing:
    docker:
      - image: cimg/base:2022.06
    environment:
      MyLastName : Aly
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace2
      - run:
          name: type my name
          command:
            cat ~/workspace2/mname.txt
      #- restore_cache:
      #    keys:
      #      - v1-my-project-{{ checksum "project.clj" }}
      #      - v1-my-project-

          
workflows:
  default: 
    jobs:
      - print
      - testSharing:
          requires:
            - print
