version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: 
          name: install node dependencies
          command: |
            npm install
      - run:
          name: build
          command: |
            npm run build
      - run:
          name: list build outputs
          command: |
            ls ./build

#workflows:
#  default: 
