version: 2.1

jobs:
  print:
    docker:
      - image: cimg/node:lts  
    environment:
      MyLastName : Aly
    steps:
      - run:
          name: type my name
          command: |
            echo "<<MyFirstName>>"
            echo $MyLastName

workflows:
  default: 
    jobs:
      - print