version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:2022.06
  working_directory: ~/project

commands:
  sayHellow:
    description: "this command to salute"
    parameters:
      to:
        type: string
        default: "my_friend"
    steps:
      - run: echo command test #<< parameters.to>>
jobs:
  print:
    docker:
      - image: cimg/base:2022.06 
    environment:
      MyLastName : Aly
    steps:
      - checkout
      - run:
          name: type my name
          command: |
            echo $MyFirstName
            echo $MyLastName
            echo "My name is hany" > ~/mname.txt
      - run:
          name: set secret key
          command: |
            curl https://kvdb.io/CMcjJfUz81PF2Q36ti3Bbe/migration_$\{CIRCLE_WORKFLOW_ID_1\}  -d '123'
      - persist_to_workspace:
          root: ~/
          paths:
            - mname.txt
            #- target/application.jar
            #- build/*

      #- save_cache:
      #    key: v1-my-project-{{ checksum "project.clj" }}
      #    paths:
      #      - ~/.m2

  testSharing:
    << : *defaults
    #docker:
    #  - image: cimg/base:2022.06
    environment:
      MyLastName : Aly ${CIRCLE_WORKFLOW_ID}
    steps:
      - checkout
      - run:
          name: get secret key value
          command:
            curl --insecure https://kvdb.io/CMcjJfUz81PF2Q36ti3Bbe/migration_$\{CIRCLE_WORKFLOW_ID_1\}
      - attach_workspace:
          at: ~/workspace
      - run:
          name: type my name
          command:
            cat ~/workspace/mname.txt
      #- restore_cache:
      #    keys:
      #      - v1-my-project-{{ checksum "project.clj" }}
      #      - v1-my-project-
  testCommand:
    <<: *defaults
    steps:
      - checkout
      - sayHellow: 
              to: "samir"

workflows:
  default: 
    jobs:
      - print
      - testSharing:
          requires:
            - print
